### PR TITLE
Reset game Feature Added

### PR DESCRIPTION
**Pull request by advait2205**
As shown below reset game feature is added to reset game.
ezgif com-gif-maker (1)

Fixes: #5

### CODE REVIEW

**Review by vidhibadrakiya — APPROVED** [review]

**Review by sarthakhp — CHANGES_REQUESTED** [review]
It is better to add Two buttons or Toggle option to select instead of having to right 'X' or 'O'  through keyboard.

**Comment by advait2205** [comment]
> It is better to add Two buttons or Toggle option to select instead of having to right 'X' or 'O' through keyboard.

So, i should make changes in PR #16 right ?

**Comment by adit19shah** [comment]
> > It is better to add Two buttons or Toggle option to select instead of having to right 'X' or 'O' through keyboard.
> 
> So, i should make changes in PR #16 right ?

Yes, it is to be done in PR #16.

**Review by adit19shah — APPROVED** [review]

**Comment by adit19shah** [comment]
LGTM, Thanks.

**Comment by advait2205** [comment]
> It is better to add Two buttons or Toggle option to select instead of having to write 'X' or 'O' through keyboard.

Okay changes in both PR #16  and PR #17 done added buttons for chhosing player.
For Screenshot see PR #16

**Review by sarthakhp — APPROVED** [review]

**Pull request merged**
